# Runs all of the scraping files in order.
directory <- "C:/Users/njcor/Documents/GitHub/mercado-libre/"
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BluetoothSpeakers/BluetoothSpeakers_Uru.R")) }, error = function(err) {})
print(Sys.time())

print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "BTHeadphones/BTHeadphones_Uru.R")) }, error = function(err) {})
print(Sys.time())

print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8PlusCases/iPhone8PlusCases_Uru.R")) }, error = function(err) {})
print(Sys.time())

print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "iPhone8Cases/iPhone8Cases_Uru.R")) }, error = function(err) {})
print(Sys.time())

print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "ElectricRazors/ElectricRazors_Uru.R")) }, error = function(err) {})
print(Sys.time())

print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Arg.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Bra.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Chi.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Col.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Mex.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Per.R")) }, error = function(err) {})
print(Sys.time())
tryCatch({ source(paste(directory, "MotorcycleHelmets/MotorcycleHelmets_Uru.R")) }, error = function(err) {})
print(Sys.time())

